version: "3.7"
services:
  api:
    image: rafaellessa/clean-api:${DOCKER_IMAGE_TAG:-latest}
    container_name: clean-api
    build:
      context: api
      dockerfile: Dockerfile          
    volumes: 
      - /app/node_modules/
      - ./api/code:/app
    ports:
      - "${CLEAN_API_PORT:-3000}:${CLEAN_API_PORT:-3000}"
    environment:
      #Mysql
      DB_HOST: service-mysql
      DB_PORT: 3306
      DB_USERNAME: ${MYSQL_DB_USERNAME}
      DB_PASSWORD: ${MYSQL_DB_PASSWORD}
      DB_DATABASE: ${MYSQL_DB_DATABASE}
       # Ambiente do node
      CLEAN_API_ENV: ${CLEAN_API_ENV}
      CLEAN_API_PORT: ${CLEAN_API_PORT}
    networks:
      - clean-network
    depends_on:
      - "mysql-db"
    restart: unless-stopped
  mysql-db:
    container_name: mysql-db
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - clean-network
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_DB_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB_DATABASE}
    restart: always
volumes:
    mysql-volume:
        driver: local
networks:
    clean-network:
        external: true